SELECT 
CONCAT('FY',ACCOUNTING_YEAR,'P',RIGHT(ACCOUNTING_PERIOD_NUMBER,2),'W',ACCOUNTING_WEEK_NUMBER) AS FY_PW, DENSE_RANK() OVER(ORDER BY FY_PW DESC) AS FYP_RANK,
       FK_CREATED_DATE,
       STATE,
       STORE_ID,
       ZONE,
       STORE_STATUS,
       ORDER_TYPE,
       AVG(AVG_AGE) AS AVG_AGE
       FROM
((SELECT 
       FK_CREATED_DATE,
       STATE,
       STORE_ID,
       ZONE,
       STORE_STATUS,
       ORDER_TYPE,
       AVG(AGE) AS AVG_AGE
FROM "KSFPA"."ONLINE_UGAM_PVT"."NATHAN_CUSTOMER_UNITS_RECEIVED"
  WHERE AGE NOT LIKE ('-%')
GROUP BY 1,2,3,4,5,6)
UNION
(SELECT
       FK_CREATED_DATE,
       STATE,
       STORE_ID,
       ZONE,
       STORE_STATUS,
       'All' AS ORDER_TYPE,
       AVG(AGE) AS AVG_AGE
FROM "KSFPA"."ONLINE_UGAM_PVT"."NATHAN_CUSTOMER_UNITS_RECEIVED"
 WHERE AGE NOT LIKE ('-%')
GROUP BY 1,2,3,4,5,6))
 INNER JOIN "KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD"."COMMON_DIMENSIONS"."DIM_DATE" DT
ON FK_CREATED_DATE=DT.DATE
WHERE ACCOUNTING_YEAR >= 2023
GROUP BY 1,3,4,5,6,7,8;