create or replace view KSFPA.ONLINE_UGAM_PVT.SUPER_DASH_CANCELLED_ORDERS_MAIN(
	YEAR,
	PERIOD,
	WEEK,
	FY_PW,
	RETURN_REASON,
	COST,
	ORDER_COUNT
) as
SELECT YEAR,
       PERIOD,
       WEEK,
       CONCAT('FY',   YEAR, 'P',RIGHT(CONCAT(0,PERIOD),2),'W', WEEK) AS FY_PW,
       RETURN_REASON,
       SUM(COST) AS COST,
       SUM(ORDER_COUNT) AS ORDER_COUNT
FROM KSFPA.ONLINE_UGAM_PVT.CANCELLED_ORDERS_MAIN1
GROUP BY 1,2,3,4,5;