create or replace view KSFPA.ONLINE_UGAM_PVT.LOST_SALES_SUPER(
	FY_PW,
	FYP_RANK,
	STORE_ID,
	STATE,
	ZONE,
	STORE_STATUS,
	CUSTOMER_ORDER_TYPE,
	LOST_SALES
) as
SELECT FY_PW,
       DENSE_RANK() OVER(ORDER BY FY_PW DESC) AS FYP_RANK,
       STORE_ID,
       (CASE WHEN STATE ='NTH' OR STATE = 'STH' THEN 'NZ' ELSE STATE END) AS STATE,
       ZONE,
       STORE_STATUS,
       CUSTOMER_ORDER_TYPE,
       SUM(LOST_SALES) AS LOST_SALES
    FROM
((SELECT FY_PW,
       STORE_ID,
       STATE,
       ZONE,
       STORE_STATUS,
       CUSTOMER_ORDER_TYPE,
       SUM(CANCELLED_LOSS_STR) + SUM(PART_CAN_LOSS) AS LOST_SALES
   FROM "KSFPA"."ONLINE_UGAM_PVT"."WEEKLY_LOST_SALES"
GROUP BY 1,2,3,4,5,6)
UNION
(SELECT FY_PW,
       STORE_ID,
       STATE,
       ZONE,
       STORE_STATUS,
       'All' AS CUSTOMER_ORDER_TYPE,
       SUM(CANCELLED_LOSS_STR) + SUM(PART_CAN_LOSS) AS LOST_SALES
   FROM "KSFPA"."ONLINE_UGAM_PVT"."WEEKLY_LOST_SALES"
GROUP BY 1,2,3,4,5,6))LS
GROUP BY 1,3,4,5,6,7;