create or replace view KSFPA.ONLINE_UGAM_PVT.WEEKLY_DIF_PERCENTAGE_SUPER(
	FY_PW,
	FYP_RANK,
	FK_CREATED_DATE,
	STATE,
	A,
	ZONE,
	STORE_STATUS,
	ORDER_TYPE,
	SUM_QTY_PCKD_TODAY,
	SUM_ORG_QTY_TODAY,
	SUM_QTY_PCKD_YEST,
	SUM_ORG_QTY_YEST
) as

(Select 
CONCAT('FY',ACCOUNTING_YEAR,'P',RIGHT(ACCOUNTING_PERIOD_NUMBER,2),'W',ACCOUNTING_WEEK_NUMBER) AS FY_PW
,DENSE_RANK() OVER(ORDER BY FY_PW DESC) AS FYP_RANK
,A.FK_CREATED_DATE
, A.STATE 
, A.STORE_ID A
, A.ZONE 
, A.STORE_STATUS 
, A.ORDER_TYPE 
, SUM(A.SUM_QUANTITY_PACKED) AS SUM_QTY_PCKD_TODAY
, SUM(A.SUM_ORIGINAL_QUANTITY) AS SUM_ORG_QTY_TODAY
, SUM(B.SUM_QUANTITY_PACKED) AS SUM_QTY_PCKD_YEST
, SUM(B.SUM_ORIGINAL_QUANTITY) AS SUM_ORG_QTY_YEST
from
(select 
FK_CREATED_DATE,
store_id,
ZONE,
STORE_STATUS,
ORDER_TYPE,
state,
SUM_ORIGINAL_QUANTITY,
SUM_QUANTITY_PICKED,
SUM_QUANTITY_PACKED,
SUM_QUANTITY_REJECTED
 FROM
  (
select 
FK_CREATED_DATE,
store_id,
ZONE,
STORE_STATUS,
ORDER_TYPE,
state,
SUM_ORIGINAL_QUANTITY,
SUM_QUANTITY_PICKED,
SUM_QUANTITY_PACKED,
SUM_QUANTITY_REJECTED
FROM "KSFPA"."ONLINE_UGAM_PVT"."NATHAN_DIF_DATA" )
 UNION 
( select 
FK_CREATED_DATE,
store_id,
ZONE,
STORE_STATUS,
'All' AS ORDER_TYPE,
state,
SUM_ORIGINAL_QUANTITY,
SUM_QUANTITY_PICKED,
SUM_QUANTITY_PACKED,
SUM_QUANTITY_REJECTED
FROM "KSFPA"."ONLINE_UGAM_PVT"."NATHAN_DIF_DATA"))A
left join (
  select 
FK_CREATED_DATE,
store_id,
ZONE,
STORE_STATUS,
ORDER_TYPE,
state,
SUM_ORIGINAL_QUANTITY,
SUM_QUANTITY_PICKED,
SUM_QUANTITY_PACKED,
SUM_QUANTITY_REJECTED
  FROM 
(select 
FK_CREATED_DATE,
store_id,
ZONE,
STORE_STATUS,
ORDER_TYPE,
state,
SUM_ORIGINAL_QUANTITY,
SUM_QUANTITY_PICKED,
SUM_QUANTITY_PACKED,
SUM_QUANTITY_REJECTED
FROM "KSFPA"."ONLINE_UGAM_PVT"."NATHAN_DIF_DATA")
UNION 
(select 
FK_CREATED_DATE,
store_id,
ZONE,
STORE_STATUS,
'All' AS ORDER_TYPE,
state,
SUM_ORIGINAL_QUANTITY,
SUM_QUANTITY_PICKED,
SUM_QUANTITY_PACKED,
SUM_QUANTITY_REJECTED
FROM "KSFPA"."ONLINE_UGAM_PVT"."NATHAN_DIF_DATA" )) B
on a.FK_CREATED_DATE-1=b.FK_CREATED_DATE
 AND A.STORE_ID=B.STORE_ID
 AND A.STATE=B.STATE
 AND A.ZONE = B.ZONE
 AND A.STORE_STATUS = B.STORE_STATUS
 AND A.ORDER_TYPE = B.ORDER_TYPE
INNER JOIN "KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD"."COMMON_DIMENSIONS"."DIM_DATE" dt
on a.FK_CREATED_DATE=dt.DATE 
GROUP BY 1,3,4,5,6,7,8);