create or replace view KSFPA.ONLINE_UGAM_PVT.SUPER_UNITS(
	FY_PW,
	FYP_RANK,
	ACCOUNTING_YEAR,
	FK_CREATED_DATE,
	STORE_ID,
	STATE,
	ORDER_TYPE,
	TOTAL_UNITS
) as
SELECT CONCAT('FY',ACCOUNTING_YEAR,'P',RIGHT(ACCOUNTING_PERIOD_NUMBER,2),'W',ACCOUNTING_WEEK_NUMBER) AS FY_PW, 
       DENSE_RANK() OVER(ORDER BY FY_PW DESC) AS FYP_RANK,
       ACCOUNTING_YEAR,
       FK_CREATED_DATE,
       STORE_ID,
       STATE,
       ORDER_TYPE,
       SUM(UNITS) AS TOTAL_UNITS
       FROM
       (SELECT FK_CREATED_DATE,
               STATE,
               STORE_ID,
               ORDER_TYPE,
               SUM(NOOFUNITS) AS UNITS
FROM "KSFPA"."ONLINE_UGAM_PVT"."NATHAN_CUSTOMER_UNITS_RECEIVED" 
WHERE STATE  NOT IN ('undefined')
        GROUP BY 1,2,3,4)A
  LEFT JOIN "KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD"."COMMON_DIMENSIONS"."DIM_DATE" D
on A.FK_CREATED_DATE=D.DATE
WHERE ACCOUNTING_YEAR >= 2023
GROUP BY 1,3,4,5,6,7;